### ISSUE TITLE
Getting Started with ML-Dash

### ISSUE THREAD

**Issue by hugoleodev** [geyang/ml_logger#36]
I have considered using ml-dash with ml-logger, but I ml-dash tutorial is not working for me. Is there a fresh example of how to use ml-logger with ml-dash?

My need is to run a ml_dash.server instance within a remote server and all applications will log to main remote ml_dash.server

**Comment by geyang** [comment]
@hugoleodev Let me whip up one real-quick today! Will get back to you tomorrow.

**Comment by hugoleodev** [comment]
@geyang nice!

**Comment by hugoleodev** [comment]
@geyang Any news about it?

**Comment by geyang** [comment]
Yes! Should be ready soon! Taking a final look before pushing.

 -- which page/URL are you looking at? This way I can better prioritize which one to update first. (github README/readthedoc etc)

**Comment by geyang** [comment]
> I have considered using ml-dash with ml-logger, but I ml-dash tutorial is not working for me. Is there a fresh example of how to use ml-logger with ml-dash?
> 
> My need is to run a ml_dash.server instance within a remote server and all applications will log to main remote ml_dash.server

So the `ml_dash.server` is separate from the `ml_logger.server`. The later is used to log, whereas the former is a visualization backend used for processing the data to server to the dashboard front end.

So to setup remote logging, inside the instrumentation server, you need to launch both servers in separate processes:

```bash
#!/usr/bin/bash
#launch-logger:
python -m ml_logger.server --data-dir ~/runs --port 8080 --host 0.0.0.0 --workers 4
```
Then in a separate process,
```bash
#launch-dash-server:
python -m ml_dash.server --logdir runs --port 8090 --host 0.0.0.0
```

Inside your client, you should put in the URL for the dashboard server as follows:

<img width="1215" alt="Screen Shot 2020-12-10 at 9 57 55 AM" src="https://user-images.githubusercontent.com/630490/101810915-38781580-3ace-11eb-8c5c-6990dd8fef59.png">

A key issue to keep in mind, is that inside your `~/runs` folder, the experiments need to be under two layers of directories:

```bash
$ tree -L 3 ~/runs
<your-username>
    <your-project-name>
       <experiment-1>
       <experiment-2>
```

This means that with ML-Logger, you need to configure the prefix so that the logging is prefixed by `{your-username}/{your-project-name}`.

**Comment by hugoleodev** [comment]
@geyang very nice! Is there any way to store metrics in a database?

I would like to create a centralized way to maintain all experiments data.

**Comment by geyang** [comment]
Hey Hugo, I currently save all data as pkl files individually, because the metrics reported by each project could be drastically different. So to collect all data, I just glob for the `metrics.pkl` file and read the content into a `Pandas.DataFrame`.

ML-Logger offers an easy way to do this:

```python
from ml_logger import logger

all_metrics = logger.read_metrics('your-prefix/project/experiment-*')
```

**Comment by hugoleodev** [comment]
HI @geyang 

I have tested your example and, As far as can see, the current architecture does not fit our needs.

We will deploy ml-logger / ml-dash within a tsuru pass, just like the Heroku pass.

To work well in tsuru, we need two apps:
- One with ml_logger.server
- One with ml_dash.server and ml_dash.app

But as you mentioned ml_dash.server and ml_logger.server needs to watch the same directory in the filesystem.

But as I have listed above, the two apps do not have the same filesystem.

I think that if ml_dash.server can connect to ml_logger.server through HTTP, the filesystem access will be only in ml_logger.server.

What do you think about it?

**Comment by hugoleodev** [comment]
@geyang 

FROM

![image](https://user-images.githubusercontent.com/1406443/102617868-9503b200-4118-11eb-86d8-152fd7c07dda.png)

TO 

![image](https://user-images.githubusercontent.com/1406443/102617976-bf556f80-4118-11eb-9246-9142cacf8e8b.png)

**Comment by geyang** [comment]
@hugoleodev Thanks for your comment! 

When logging experiments the amount of storage can grow very quickly if you are saving checkpoints. For this reason, when I deploy on AWS, I attach an EBS as persistent storage that life-cycles independently from the EC2 instances. When you run tsuru process, what kind of strategy do you adopt for persistent storage? 

If I were using docker, I would mount the same volume to the two docker processes. I expect tsuru process to expose similar APIs to physical volumes or EBS, that you can configure to point to the same physical drive. I can also see how the second architecture is more convenient :) The way I would go about it would be to create an AsyncFile API that abstracts away file access :)

**Comment by geyang** [comment]
I did some search, do you think configurations in this thread would help?

https://github.com/tsuru/tsuru/issues/1294

**Comment by hugoleodev** [comment]
Hi @geyang, me again.

Right,

I have set up our tsuru app to work with a shared filer mounted on the $HOME/runs folder.

And now it works!!!!

But the example does not show any chart with the example that you show above 

Can you help me with it?

**Comment by hugoleodev** [comment]
@geyang Here is the error in ml-dash front

![image](https://user-images.githubusercontent.com/1406443/103234152-ab321f00-491d-11eb-8fc4-382ff0246e65.png)

**Comment by geyang** [comment]
@hugoleodev Great job getting the example to run! The error message might be benign (it does not really do much). To configure the line plot, you need to put the following into the `.charts` file:

```yaml
charts:
- yKey: loss
  xKey: epoch
```
